services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/conf:/etc/caddy
      - $PWD/site:/srv
      - /home/braden/caddy/data:/data
      - /home/braden/caddy/config:/config
